// import React from "react";
// import { ApolloProvider } from "@apollo/client";
// import { Provider } from "react-redux";
// import store from "../redux/store.js";
// import client from "./lib/apolloClient.js";

// function MyApp({ Component, pageProps }) {
//   return (
//     <Provider store={store}>
//       <ApolloProvider client={client}>
//         <Component {...pageProps} />
//       </ApolloProvider>
//     </Provider>
//   );
// }

// export default MyApp;

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
